/*
===========================================================
PROJECT: Supply Chain Analytics (End-to-End SQL Project)
AUTHOR: Ashutosh Jamnal
TOOLS: MySQL, Excel, Power BI

DESCRIPTION:
This project analyzes supply chain performance, delivery efficiency,
profitability, and customer behavior.

OBJECTIVE:
- Reduce late deliveries
- Improve profitability
- Identify high-performing products & regions
- Detect operational inefficiencies
===========================================================
*/


/*
===========================================================
BUSINESS PROBLEM
===========================================================

The company is facing:
- High late deliveries
- Profit inconsistencies
- Regional inefficiencies
- Fraud risk in orders

Goal:
Build a data-driven analytics system to optimize supply chain operations.
===========================================================
*/


-- SECTION 1: CORE KPI ANALYSIS

-- What is the total revenue generated by the business?
SELECT
	SUM(sales_amount) AS total_revenue
FROM fact_order_items;

-- What is the total profit earned across all orders/
SELECT
	SUM(profit_amount) AS total_profit
FROM fact_order_items;

-- What percentage of revenue is converted into profit?
SELECT
	ROUND(SUM(profit_amount)/SUM(sales_amount)*100,2) AS profit_margin_pct
FROM fact_order_items;

-- KPI: How many unique orders have been placed?
SELECT
	COUNT(DISTINCT order_id) as total_order
FROM fact_order_items;

-- KPI: What is the average revenue generated per order?
SELECT 
    SUM(sales_amount) / COUNT(DISTINCT order_id) AS avg_order_value
FROM fact_order_items;


-- SECTION 2: DELIVERY PERFORMANCE

-- What percentage of total orders are delivered late?
SELECT 
    ROUND(SUM(CASE WHEN late_delivery_flag = 1 THEN 1 ELSE 0 END) 
    / COUNT(*) * 100, 2) AS late_delivery_rate
FROM fact_order_items;

-- For delayed orders, how many days late are deliveries on average?
SELECT
	AVG(shipping_days_actual - shipping_days_scheduled) as avg_delay_days
FROM fact_order_items
WHERE late_delivery_flag = 1;

-- How are deliveries distributed across Early, On-Time, and Late categories?
SELECT
	CASE
		WHEN shipping_days_actual < shipping_days_scheduled THEN 'Early'
        WHEN shipping_days_actual > shipping_days_scheduled THEN 'Late'
        ELSE 'On Time'
	END AS delivery_status,
    count(*) AS total_orders
FROM fact_order_items
GROUP BY delivery_status;

-- Which regions experience the highest late delivery rates?
SELECT 
	o.order_region,
    ROUND(SUM(f.late_delivery_flag)/COUNT(*) * 100,2) AS late_delivery_by_region
FROM fact_order_items AS f
INNER JOIN dim_order AS o 
ON o.order_id=f.order_id
GROUP BY o.order_region
ORDER BY late_delivery_by_region DESC;
	

-- SECTION 3: DIAGNOSTIC ANALYSIS

-- Which shipping mode contributes the most to overall profit?
SELECT 
    o.shipping_mode,
    SUM(f.profit_amount) AS total_profit
FROM fact_order_items f
JOIN dim_order o ON f.order_id = o.order_id
GROUP BY o.shipping_mode
ORDER BY total_profit DESC;

-- How does discount level affect profitability?	
SELECT 
    CASE 
        WHEN discount_rate = 0 THEN 'No Discount'
        WHEN discount_rate <= 0.1 THEN 'Low Discount'
        WHEN discount_rate <= 0.3 THEN 'Medium Discount'
        ELSE 'High Discount'
    END AS discount_category,
    AVG(profit_amount) AS avg_profit
FROM fact_order_items
GROUP BY discount_category;

-- What percentage of orders are generating losses?    
SELECT 
    ROUND(SUM(CASE WHEN profit_amount < 0 THEN 1 ELSE 0 END)/COUNT(*)*100,2) AS loss_order_pct
FROM fact_order_items;


-- SECTION 4: PERFORMANCE ANALYSIS

-- Which products generate the highest revenue?
SELECT
	p.product_name,
    SUM(f.sales_amount) AS revenue
FROM fact_order_items AS f
INNER JOIN dim_product AS p
ON p.product_id=f.product_id
GROUP BY p.product_name
ORDER BY revenue DESC
LIMIT 10;

-- Which products are least profitable or generating losses?
SELECT
	p.product_name,
    SUM(f.sales_amount) AS revenue
FROM fact_order_items AS f
INNER JOIN dim_product AS p
ON p.product_id=f.product_id
GROUP BY p.product_name
ORDER BY revenue ASC
LIMIT 10;

-- Who are the top customers based on revenue contribution?
SELECT 
    customer_id,
    SUM(sales_amount) AS revenue,
    RANK() OVER (ORDER BY SUM(sales_amount) DESC) AS rank_customer
FROM fact_order_items
GROUP BY customer_id;

-- SECTION 5: ADVANCED ANALYTICS

-- How is cumulative revenue growing over time?
SELECT 
    DATE(order_date) AS order_day,
    SUM(SUM(sales_amount)) OVER (ORDER BY DATE(order_date)) AS running_revenue
FROM fact_order_items
GROUP BY DATE(order_date);

-- What is the month-wise revenue trend?
WITH monthly_sales as (
	SELECT DATE_FORMAT(order_date,'%Y-%m') AS month,
    SUM(sales_amount) as revenue
FROM fact_order_items
GROUP BY month
)
SELECT * FROM monthly_sales;

-- Which region generates the highest revenue within each market?
WITH region_sales AS (
	SELECT 
		o.market,
        o.order_region,
        SUM(f.sales_amount) AS revenue
	FROM fact_order_items AS f
    INNER JOIN dim_order AS o
    ON f.order_id=o.order_id
    GROUP BY o.market,o.order_region		
)
SELECT *
FROM (
		SELECT *,
					RANK() OVER(PARTITION BY market ORDER BY revenue DESC) AS rnk
		FROM region_sales
        ) AS t
WHERE rnk = 1
;

-- How can orders be segmented into profitability tiers?
SELECT 
		order_item_id,
        profit_amount,
        NTILE(4) OVER(ORDER BY profit_amount DESC) AS profit_quartile
FROM fact_order_items;

-- What percentage of orders are international (cross-border)?
SELECT 
	ROUND(
		SUM(CASE WHEN o.order_country <> c.customer_country THEN 1 ELSE 0 END)/
        COUNT(*) * 100,2) AS cross_border_prcnt
FROM fact_order_items f
INNER JOIN dim_customer c ON f.customer_id = c.customer_id
INNER JOIN dim_order o ON f.order_id = o.order_id;

-- How many orders are suspected as fraud and what is their financial impact?

SELECT 
    COUNT(DISTINCT f.order_id) AS fraud_orders,
    SUM(CASE WHEN f.profit_amount < 0 THEN f.profit_amount ELSE 0 END) AS total_loss,
    SUM(CASE WHEN f.profit_amount > 0 THEN f.profit_amount ELSE 0 END) AS total_profit,
    SUM(f.profit_amount) AS net_impact
FROM fact_order_items f
JOIN dim_order o ON f.order_id = o.order_id
WHERE o.order_status = 'SUSPECTED FRAUD';

-- Which orders are performing better than average profitability?
SELECT 
		order_item_id,
        profit_amount
FROM fact_order_items
WHERE profit_amount> ( SELECT AVG(profit_amount) 
		FROM fact_order_items);
        
-- What percentage of total revenue is contributed by each product?
SELECT
		p.product_id,
        p.product_name,
        SUM(f.sales_amount) AS revenue,
        ROUND(SUM(f.sales_amount)/(SELECT SUM(sales_amount) FROM fact_order_items)*100,2) AS contribution_pct
FROM dim_product AS p
INNER JOIN fact_order_items AS f
ON f.product_id=p.product_id
GROUP BY p.product_id;

-- How can orders be categorized into loss, low profit,and
-- high profit segments to identify profitability distribution?
DELIMITER $$

CREATE FUNCTION profit_category(profit DECIMAL(10,2))
RETURNS VARCHAR(20)
DETERMINISTIC
BEGIN
	RETURN CASE
		WHEN profit < 0 THEN 'Loss'
        WHEN profit BETWEEN 0 AND 50 THEN 'Low Profit'
        ELSE 'High Profit'
	END;
END $$

DELIMITER ;

SELECT 
    order_item_id,
    profit_amount,
    profit_category(profit_amount) AS profit_segment
FROM fact_order_items;

SELECT 
    profit_category(profit_amount) AS profit_segment,
    COUNT(*) AS total_orders,
    ROUND(COUNT(*) * 100 / (SELECT COUNT(*) FROM fact_order_items), 2) AS percentage
FROM fact_order_items
GROUP BY profit_segment
ORDER BY percentage DESC;


        
        
		



